-- QUERY HORAS EM MANUTENÇÃO - AGREGADA PARA DASHBOARD V2
-- THIAGO SIRIAKI VALENTINI 26/01/2026
-- V1.0 -- DESENVOLVIMENTO QUERY INICIAL
-- V1.1 -- QUANDO OCORRE VIRADA DE MÊS, CALCULA AS HORAS EM MANUTENÇÃO EM CADA MÊS.
-- V1.2 -- AJUSTADA DATA DE COMPETÊNCIA PARA ANÁLISE POR MÊS EM MANUTENÇÃO.
-- V2.0 -- QUERY AGREGADA PARA DASHBOARD COM TOTAIS E MÉTRICAS
-- V2.1 -- REMOVIDAS PLACAS ESPECÍFICAS

---------- ########## S I T U A Ç Ã O  V E I C U L O ########## ----------
WITH SITUACAO_VEIC AS (

SELECT

  OPER.VEICULO.COD_VEICULO
, OPER.VEICULO.COD_GESTAO
, OPER.VEICULO.PLACA
, OPER.VEICULO.ANO
, OPER.VEICULO_MARCA.MARCA 
, OPER.VEICULO_SITUACAO.SITUACAO
, ROW_NUMBER() OVER (
        PARTITION BY OPER.VEICULO.COD_VEICULO
        ORDER BY OPER.VEICULO_HIST_SITUACAO.DATA DESC
    ) AS ULT_EVENTO
, OPER.VEICULO_AGRUPAMENTO.DESCRICAO AS AGRUPAMENTO
, OPER.VEICULO_AGRUPAMENTO.AGRUPAMENTO_ID
, OPER.VEICULO_ULTIMO_KM.KM AS ULTIMO_KM
, CASE WHEN OPER.VEICULO_AGRUPAMENTO.AGRUPAMENTO_ID IN (15, 14, 16, 1) 
	   THEN 'CM' ELSE 'SR' END AS TIPO_VEICULO

FROM

OPER.VEICULO 

JOIN OPER.VEICULO_MARCA
ON OPER.VEICULO_MARCA.MARCA_ID = OPER.VEICULO.MARCA_ID 

LEFT JOIN OPER.VEICULO_HIST_SITUACAO
ON OPER.VEICULO_HIST_SITUACAO.COD_GESTAO = OPER.VEICULO.COD_GESTAO
AND OPER.VEICULO_HIST_SITUACAO.PLACA = OPER.VEICULO.PLACA 

JOIN OPER.VEICULO_SITUACAO
ON OPER.VEICULO_SITUACAO.SITUACAO_ID = OPER.VEICULO_HIST_SITUACAO.SITUACAO_ID

JOIN OPER.VEICULO_TIPO_CARROCERIA
ON OPER.VEICULO_TIPO_CARROCERIA.COD_GESTAO = OPER.VEICULO.COD_GESTAO
AND OPER.VEICULO_TIPO_CARROCERIA.TIPO_CARROCERIA_ID = OPER.VEICULO.TIPO_CARROCERIA_ID

JOIN OPER.VEICULO_AGRUPAMENTO
ON OPER.VEICULO_AGRUPAMENTO.AGRUPAMENTO_ID = OPER.VEICULO_TIPO_CARROCERIA.AGRUPAMENTO_ID

LEFT JOIN OPER.VEICULO_ULTIMO_KM
ON OPER.VEICULO_ULTIMO_KM.COD_GESTAO = OPER.VEICULO.COD_GESTAO
AND OPER.VEICULO_ULTIMO_KM.PLACA = OPER.VEICULO.PLACA

WHERE

OPER.VEICULO.COD_GESTAO = 99935
AND OPER.VEICULO_HIST_SITUACAO.DATA_CANCELAMENTO IS NULL

),

---------- ########## C A L C U L O  H O R A S  M A N U T E N Ç Ã O ########## ----------
BASE_OS AS (
SELECT
  MANUTENCAO.EQUIPAMENTO_TABELA_MANUT.EQUIPAMENTO_ID
, MANUTENCAO.EQUIPAMENTO_TABELA_MANUT.COD_GESTAO
, ALMOXARIFADO.EQUIPAMENTO.PLACA
, MANUTENCAO.EQUIPAMENTO_TABELA_MANUT.ORDEM_SERVICO_ID_EXECUCAO
, MANUTENCAO.ORDEM_SERVICO.DATA_ABERTURA
, MANUTENCAO.ORDEM_SERVICO.DATA_ATENDIMENTO
, MANUTENCAO.ORDEM_SERVICO.DATA_FECHAMENTO

FROM 
MANUTENCAO.EQUIPAMENTO_TABELA_MANUT

LEFT JOIN ALMOXARIFADO.EQUIPAMENTO
ON ALMOXARIFADO.EQUIPAMENTO.COD_GESTAO = MANUTENCAO.EQUIPAMENTO_TABELA_MANUT.COD_GESTAO
AND ALMOXARIFADO.EQUIPAMENTO.EQUIPAMENTO_ID = MANUTENCAO.EQUIPAMENTO_TABELA_MANUT.EQUIPAMENTO_ID

LEFT JOIN MANUTENCAO.ORDEM_SERVICO
ON MANUTENCAO.ORDEM_SERVICO.COD_GESTAO = MANUTENCAO.EQUIPAMENTO_TABELA_MANUT.COD_GESTAO
AND MANUTENCAO.ORDEM_SERVICO.ORDEM_SERVICO_ID = MANUTENCAO.EQUIPAMENTO_TABELA_MANUT.ORDEM_SERVICO_ID_EXECUCAO

WHERE 
    MANUTENCAO.EQUIPAMENTO_TABELA_MANUT.DATA_CANCELAMENTO IS NULL
AND MANUTENCAO.EQUIPAMENTO_TABELA_MANUT.REG_ATUAL <> 1
AND MANUTENCAO.ORDEM_SERVICO.DATA_ABERTURA >= DATE '2025-01-01'
AND MANUTENCAO.ORDEM_SERVICO.DATA_ATENDIMENTO IS NOT NULL 
AND MANUTENCAO.ORDEM_SERVICO.DATA_FECHAMENTO IS NOT NULL

), GERADOR_MESES (

  EQUIPAMENTO_ID
, COD_GESTAO
, PLACA
, ORDEM_SERVICO_ID_EXECUCAO
, DATA_ABERTURA
, DATA_ATENDIMENTO
, DATA_FECHAMENTO
, INICIO_TRECHO
, MES_REF) AS (

SELECT

  BASE_OS.EQUIPAMENTO_ID
, BASE_OS.COD_GESTAO
, BASE_OS.PLACA
, BASE_OS.ORDEM_SERVICO_ID_EXECUCAO
, BASE_OS.DATA_ABERTURA
, BASE_OS.DATA_ATENDIMENTO
, BASE_OS.DATA_FECHAMENTO
, BASE_OS.DATA_ATENDIMENTO AS INICIO_TRECHO
, TRUNC(BASE_OS.DATA_ATENDIMENTO, 'MM') AS MES_REF

FROM 
BASE_OS

UNION ALL

SELECT

  GERADOR_MESES.EQUIPAMENTO_ID
, GERADOR_MESES.COD_GESTAO
, GERADOR_MESES.PLACA
, GERADOR_MESES.ORDEM_SERVICO_ID_EXECUCAO
, GERADOR_MESES.DATA_ABERTURA
, GERADOR_MESES.DATA_ATENDIMENTO
, GERADOR_MESES.DATA_FECHAMENTO
, ADD_MONTHS(GERADOR_MESES.MES_REF, 1) AS INICIO_TRECHO
, ADD_MONTHS(GERADOR_MESES.MES_REF, 1) AS MES_REF

FROM 
GERADOR_MESES

WHERE 
LAST_DAY(GERADOR_MESES.MES_REF) + 1 <= GERADOR_MESES.DATA_FECHAMENTO

), TEMPO_MANUTENCAO AS (

SELECT 

  GERADOR_MESES.EQUIPAMENTO_ID
, GERADOR_MESES.COD_GESTAO
, GERADOR_MESES.PLACA
, GERADOR_MESES.ORDEM_SERVICO_ID_EXECUCAO
, GERADOR_MESES.DATA_ABERTURA
, GERADOR_MESES.DATA_ATENDIMENTO
, GERADOR_MESES.DATA_FECHAMENTO
, TRUNC(GERADOR_MESES.MES_REF, 'MM') AS MES_COMPETENCIA
, (LEAST(GERADOR_MESES.DATA_FECHAMENTO, LAST_DAY(GERADOR_MESES.MES_REF) + 1) - GERADOR_MESES.INICIO_TRECHO) * 24 AS HORAS_MANUTENCAO_MES
, EXTRACT(DAY FROM LAST_DAY(GERADOR_MESES.MES_REF)) * 24 AS TOTAL_HORAS_MES_REF

FROM 
GERADOR_MESES

ORDER BY
  GERADOR_MESES.EQUIPAMENTO_ID
, GERADOR_MESES.MES_REF

),

---------- ########## MÉTRICAS AGREGADAS ########## ----------
METRICAS_BASE AS (

SELECT DISTINCT

  TEMPO_MANUTENCAO.EQUIPAMENTO_ID
, TEMPO_MANUTENCAO.COD_GESTAO
, TEMPO_MANUTENCAO.PLACA
, TEMPO_MANUTENCAO.ORDEM_SERVICO_ID_EXECUCAO
, TEMPO_MANUTENCAO.DATA_ABERTURA
, TEMPO_MANUTENCAO.DATA_ATENDIMENTO
, TEMPO_MANUTENCAO.DATA_FECHAMENTO
, TEMPO_MANUTENCAO.MES_COMPETENCIA
, TEMPO_MANUTENCAO.HORAS_MANUTENCAO_MES
, TEMPO_MANUTENCAO.TOTAL_HORAS_MES_REF
, SITUACAO_VEIC.AGRUPAMENTO
, SITUACAO_VEIC.TIPO_VEICULO

FROM
TEMPO_MANUTENCAO

LEFT JOIN SITUACAO_VEIC
ON SITUACAO_VEIC.COD_GESTAO = TEMPO_MANUTENCAO.COD_GESTAO 
AND SITUACAO_VEIC.PLACA = TEMPO_MANUTENCAO.PLACA

),

---------- ########## CÁLCULOS AGREGADOS ########## ----------
AGREGADOS AS (

SELECT

-- TOTAL DE VEÍCULOS
COUNT(DISTINCT PLACA) AS TOTAL_VEICULOS,

-- VEÍCULOS EM MANUTENÇÃO (últimos 30 dias)
COUNT(DISTINCT CASE WHEN DATA_FECHAMENTO >= SYSDATE - 30 THEN PLACA END) AS VEICULOS_MANUTENCAO_30D,

-- TOTAL DE HORAS EM MANUTENÇÃO
ROUND(SUM(HORAS_MANUTENCAO_MES), 2) AS TOTAL_HORAS_MANUTENCAO,

-- TOTAL GERAL DE HORAS (horas disponíveis no período)
ROUND(SUM(TOTAL_HORAS_MES_REF), 2) AS TOTAL_GERAL_HORAS,

-- MÉDIA DE HORAS POR VEÍCULO
ROUND(AVG(HORAS_MANUTENCAO_MES), 2) AS MEDIA_HORAS_POR_VEICULO,

-- DIAS EM MANUTENÇÃO (últimos 30 dias)
COUNT(DISTINCT TRUNC(DATA_FECHAMENTO)) AS DIAS_MANUTENCAO,

-- MANUTENÇÕES CONCLUÍDAS
COUNT(DISTINCT ORDEM_SERVICO_ID_EXECUCAO) AS MANUTENCOES_CONCLUIDAS,

-- MANUTENÇÕES TOTAIS (para cálculo de percentual)
COUNT(DISTINCT ORDEM_SERVICO_ID_EXECUCAO) AS TOTAL_MANUTENCOES

FROM METRICAS_BASE

WHERE DATA_FECHAMENTO >= DATE '2025-01-01'

),

---------- ########## TENDÊNCIA MENSAL ########## ----------
TENDENCIA_MENSAL AS (

SELECT

-- MÊS ANTERIOR
ROUND(AVG(HORAS_MANUTENCAO_MES), 2) AS MEDIA_MES_ANTERIOR

FROM METRICAS_BASE

WHERE MES_COMPETENCIA >= ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -2)
AND MES_COMPETENCIA < TRUNC(SYSDATE, 'MM')

)

---------- ########## RESULTADO FINAL ########## ----------
SELECT

-- MÉTRICAS PRINCIPAIS
TOTAL_VEICULOS,
ROUND((VEICULOS_MANUTENCAO_30D * 100.0 / NULLIF(TOTAL_VEICULOS, 0)), 2) AS PERCENTUAL_MANUTENCAO,
TOTAL_HORAS_MANUTENCAO,
TOTAL_GERAL_HORAS,
MEDIA_HORAS_POR_VEICULO,
DIAS_MANUTENCAO,
MANUTENCOES_CONCLUIDAS,

-- TENDÊNCIA MENSAL
CASE 
    WHEN (SELECT MEDIA_MES_ANTERIOR FROM TENDENCIA_MENSAL) > 0 THEN
        ROUND(((SELECT AVG(HORAS_MANUTENCAO_MES) FROM METRICAS_BASE 
              WHERE MES_COMPETENCIA >= TRUNC(SYSDATE, 'MM')) / 
              (SELECT MEDIA_MES_ANTERIOR FROM TENDENCIA_MENSAL) - 1) * 100, 2)
    ELSE 0 
END AS TENDENCIA_MENSAL

FROM AGREGADOS;
